use crate::{deserialize, serialize};
use super::*;

//
// MARK: 0x01 Encryption Request
//

/// Docstrings are copied from https://minecraft.wiki/w/Java_Edition_protocol/Packets#Encryption_Request
#[derive(Debug, Clone)]
pub struct EncryptionRequest {
	/// Always empty when sent by the vanilla server.
	pub server_id: String,
	/// The server's public key, in bytes.
	pub public_key: Vec<u8>,
	/// A sequence of random bytes generated by the server.
	pub verify_token: Vec<u8>,
	/// Whether the client should attempt to authenticate through mojang servers.
	pub should_authenticate: bool,
}

impl Packet for EncryptionRequest {
	const PACKET_ID: u8 = 0x01;
	fn get_target() -> PacketTarget { PacketTarget::Client }
	fn get_state() -> ConnectionState { ConnectionState::Login }
}

impl TryFrom<EncryptionRequest> for Vec<u8> {
	type Error = Box<dyn Error>;

	fn try_from(value: EncryptionRequest) -> Result<Self, Box<dyn Error>> {
		let mut result: Vec<u8> = Vec::new();

		let public_key_length = value.public_key.len() as i32;
		let verify_token_length = value.verify_token.len() as i32;

		result.append(&mut serialize::string(&value.server_id));
		result.append(&mut serialize::prefixed_array(value.public_key, public_key_length));
		result.append(&mut serialize::prefixed_array(value.verify_token, verify_token_length));
		result.append(&mut serialize::boolean(value.should_authenticate));

		return Ok(result);
	}
}

impl TryFrom<Vec<u8>> for EncryptionRequest {
	type Error = Box<dyn Error>;

	fn try_from(mut value: Vec<u8>) -> Result<Self, Box<dyn Error>> {
		return Ok(EncryptionRequest {
			server_id: deserialize::string(&mut value)?,
			public_key: deserialize::prefixed_array(&mut value)?,
			verify_token: deserialize::prefixed_array(&mut value)?,
			should_authenticate: deserialize::boolean(&mut value)?,
		})
	}
}

//
// MARK: 0x02 Login Success
//

#[derive(Debug, Clone)]
pub struct LoginSuccess {
	pub uuid: u128,
	pub username: String,
	//TODO: missing properties array: https://minecraft.wiki/w/Java_Edition_protocol#Login_Success
}

impl Packet for LoginSuccess {
	const PACKET_ID: u8 = 0x02;
  fn get_target() -> PacketTarget { PacketTarget::Client }
  fn get_state() -> ConnectionState { ConnectionState::Login }
}

impl TryFrom<LoginSuccess> for Vec<u8> {
	type Error = Box<dyn Error>;

	fn try_from(value: LoginSuccess) -> Result<Self, Box<dyn Error>> {
		let mut result: Vec<u8> = Vec::new();

		result.append(&mut serialize::uuid(&value.uuid));
		result.append(&mut serialize::string(&value.username));
		result.push(0x00); //dont send properties array

		return Ok(result);
	}
}

impl TryFrom<Vec<u8>> for LoginSuccess {
	type Error = Box<dyn Error>;

	fn try_from(mut value: Vec<u8>) -> Result<Self, Box<dyn Error>> {
		let uuid = deserialize::uuid(&mut value)?;
		return Ok(LoginSuccess {
			uuid,
			username: deserialize::string(&mut value)?,
		})
	}
}
